# Generated by Django 4.0.3 on 2022-03-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
