# Generated by Django 4.0.3 on 2022-04-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='money',
            new_name='amount',
        ),
    ]
