# Generated by Django 4.0.3 on 2022-03-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase',
            table='purchases',
        ),
    ]
